### ISSUE TITLE
Please provide the source code?

### ISSUE THREAD

**Issue by toonymak1993** [Kosnix/SteamOsWindows#1]
Hello can you please provide the source code?
I would also like to collaborate and support the project. I have a few ideas that I want to add via powershell. Autofetch games from other launchers when starting as an example.

**Comment by toonymak1993** [comment]
I would be happy about that, then I could take a look at it and work on it. Do you have any objection to implementing this in powershell, i.e. practically as a kind of gui with which the user can choose for the initial setup?
With the SRM you could offer automatic game imports from other stores, just take a look at my repo for that and other features, I find the topic extremely exciting.

**Comment by Kosnix** [comment]
I added the files. I have no objection to using powershell as long as it remains invisible when launching steam

**Comment by toonymak1993** [comment]
Hello Kosnix, would you like to work on the version? I primarily develop with powershell and powershell studio.
I'm currently trying to implement your code in Powershell.
I would be happy to send you the Gui. My English isn't the best, but we can definitely chat.
